name: ramas_git
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State Management
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  
  # Routing
  go_router: ^14.1.1
  
  # Code Generation (Runtime)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # File System & Processes
  path: ^1.9.0
  process_run: ^1.2.4 # For running git commands
  file_picker: ^8.0.3 # For picking repositories/folders
  
  # Local Storage
  hive: ^2.2.3

  # Graph Visualization
  graphview: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation (Build Time)
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
